### ISSUE TITLE
[JSON to XML and Upload to FTP] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by isuruuy429** [wso2/ballerina-integrator#634]
**Description:**
Once a project is created through '_JSON to XML Transformation and upload to FTP_' template using dashboard and trying to run the jar, it is getting the following error. 

```
[2019-11-25 13:56:50,705] SEVERE {b7a.log.crash} - org.ballerinalang.jvm.types.BRecordType.<init>(Ljava/lang/String;Lorg/ballerinalang/jvm/types/BPackage;IZI)V 
java.lang.NoSuchMethodError: org.ballerinalang.jvm.types.BRecordType.<init>(Ljava/lang/String;Lorg/ballerinalang/jvm/types/BPackage;IZI)V
	at ballerina.lang_annotations.___init.$createTypeInstances(lang.annotations)
	at ballerina.lang_annotations.___init.$createTypes(lang.annotations)
	at ballerina.lang_annotations.___init.$currentModuleInit(lang.annotations)
	at ballerina.lang_annotations.___init.ballerina_lang_annotations__init_(lang.annotations:65535)
	at isuruuyanage.upload_to_ftp.___init.$moduleInit(upload_to_ftp:65535)
	at isuruuyanage.upload_to_ftp.___init.$lambda$$moduleInit$(upload_to_ftp)
	at org.ballerinalang.jvm.scheduling.SchedulerItem.execute(Scheduler.java:486)
	at org.ballerinalang.jvm.scheduling.Scheduler.run(Scheduler.java:237)
	at org.ballerinalang.jvm.scheduling.Scheduler.runSafely(Scheduler.java:207)
	at java.lang.Thread.run(Thread.java:748)
```

**Suggested Labels:**
Priority/high
severity/major

**Suggested Assignees:**
@MalshaL 

**Steps to reproduce:**
1. Open the Dashboard through VS Code. 
2. Select JSON to XML Transformation and upload to FTP template and create a new project. 
3. Encrypt the credentials using the following command. 
> ballerina encrypt

3. Provide the credentials of FTP server in ballerina.conf file as below. 
```
[ftp]
  host="192.168.112.3"
  port=21
  username="@encrypted:{n0JmdSKNikswPHQ/RIBkdlgBIJSCX7DpUzryLliG7T8=}"
  password="@encrypted:{n0JmdSKNikswPHQ/RIBkdlgBIJSCX7DpUzryLliG7T8=}"
```

4. Build the module 
5. Run the jar to start the service. 

**Expected**: The service should be started
**Actual**: Getting the above mentioned error in ballerina-internal.log file

**Comment by MalshaL** [comment]
This error reproduces on Ballerina version 1.0.3 and 1.0.4 but does not occur on 1.0.1.

**Comment by MalshaL** [comment]
Error occurs when the imported FTP module version has been built in a different Ballerina version from the one that is used for building the template. 
Issue to display an error message: https://github.com/ballerina-platform/ballerina-lang/issues/20068

**Comment by isuruuy429** [comment]
The same issue occurs in Samba Connector as well. 
https://ei.docs.wso2.com/en/latest/ballerina-integrator/learn/tutorials/file-based-integrations/file-integration-using-smb/1/
